### PR TITLE
Snazz up examples

### PR DESCRIPTION
**Pull request by bobcatfish**
- Add pictures to README.
- Rearrange README instructions to be clearer.
- Clearly list supported environments, remove docker machine support which wasn't documented enough for folks to be able to use (yet)
- Add support for travis

@mtomwing could you review this on Monday? I'm going to be presenting it in Dublin (at Dublin time) on Wednesday.

@mtomwing - I was unable to get this running with docker-machine at all, could you take a look? It seems like the support for docker-machine hinges on `example.docker` being resolvable, but I don't see how that's possible. (Also I couldn't get it to work with the docker beta at all, though maybe what I'm missing for the docker-machine support will work for the beta also - [forum post re. issues with accessing containers by IP with docker beta](https://forums.docker.com/t/host-excluded-from-bridge-network/12015))

### CODE REVIEW

**Comment by mtomwing** [comment]
@bobcatfish the `example.docker` thing relies on another container (https://github.com/codekitchen/dinghy-http-proxy) and it only works with dinghy currently.

If we target the Docker for Mac beta then we can do away with that entirely and just grab the container's IP address.

I guess it's possible to also target a generic `docker-machine` install, but we'd have to expose the container's port on the host to be able to get at it.

**Comment by bobcatfish** [comment]
@mtomwing was there anything in our instructions that I missed about how to run that other container?

If not I guess I have to take a look at https://github.com/codekitchen/dinghy-http-proxy#os-x and add something to our instructions?

**Comment by mtomwing** [comment]
@bobcatfish maybe lets avoid that avenue all together.

**Comment by bobcatfish** [comment]
> @bobcatfish maybe lets avoid that avenue all together.

Should we just say that we only support Linux in that case? I can add some notes to the README to refer to the `dingy-http-proxy` solution if folks want to support machine + beta.

**Comment by mtomwing** [comment]
`dinghy-http-proxy` is only useful with dinghy TBH. On other setups you'd have to manually configure your host's DNS to resolve the `.docker` domains too.

Maybe we should add a global pytest flag or something? (--docker-mode=dingy|machine|native)

**Comment by bobcatfish** [comment]
@mtomwing if you want to add that pytest flag I think that'd be handy! In the meantime I'll remove the support from the examples until we have it well documented

**Comment by mtomwing** [comment]
@bobcatfish sounds good!

**Pull request merged**
